# Generated by Django 3.1.1 on 2020-10-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0008_auto_20201025_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='time',
            field=models.DateTimeField(auto_now=True, verbose_name='content'),
        ),
    ]
